<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Util\Util.fsproj" />
    <ProjectReference Include="..\BizShared\BizShared.fsproj" />
  </ItemGroup>

</Project>
