<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\UtilKestrel\UtilKestrel.fsproj" />
    <ProjectReference Include="..\..\Common\Util\Util.fsproj" />
    <ProjectReference Include="..\JCS.BizLogics\JCS.BizLogics.fsproj" />
  </ItemGroup>

</Project>
