module TypeSys.Deploy

// TypeSys 生成物的「落地」流水线：暂存隔离 → 生成 → Native 归位 → 行尾规范化 → 额外 open 注入 → 写回/比对。
// 此前 WYI / Aiarwa / jCopilot 各有一份 Run-TypeSys-*.fsx 平行实现，差异只在下面 Profile 的四个字段；
// 现收敛到本模块作单一实现，项目脚本与 Runner.fsx 一律委托此处，避免再度漂移。

open System
open System.IO
open System.Text

open TypeSys.Config

open Util.Rdbms

type Mode =
  | Check
  | Write

/// 各项目在落地方式上的差异。config.mainDir / JsDir 必须是**在线**目录（Design-*.json 真源 + 写回目标）。
type Profile = {
  config: RobotConfig
  projectRoot: string
  banner: bool                        // true → 生成物首行插 `AUTO-GENERATED ...` 横幅（Aiarwa）
  writeTypesFs: bool                  // true → Types.fs 列入写回清单（Aiarwa）；false → 手写文件不动
  injectOpens: (string * string) list // (文件名后缀, 注入行)：写盘前插进 `//[Reserved]{` 之后
  strictCheck: bool }                 // true → --check 要求在线文件已是规范形态（Aiarwa 原口径）；
                                      // false → 只要求「规范化后等价」（WYI / jCopilot 原口径）

/// 生成物清单：(暂存文件, 在线文件, 注释前缀)。前缀供横幅使用（SQL 用 "--"）。
let output__pairs profile stagingSharedDir stagingJsDir stagingNativeFile liveNativeFile =
  let sh = profile.config.mainDir
  let js = profile.config.JsDir
  let core =
    [ Path.Combine(stagingSharedDir, "OrmTypes.fs"), Path.Combine(sh, "OrmTypes.fs"), "//"
      Path.Combine(stagingSharedDir, "OrmMor.fs"), Path.Combine(sh, "OrmMor.fs"), "//"
      Path.Combine(stagingSharedDir, "CustomMor.fs"), Path.Combine(sh, "CustomMor.fs"), "//"
      Path.Combine(stagingSharedDir, "sqlPostgreSQL.sql"), Path.Combine(sh, "sqlPostgreSQL.sql"), "--"
      Path.Combine(stagingSharedDir, "sqlSQLServer.sql"), Path.Combine(sh, "sqlSQLServer.sql"), "--"
      stagingNativeFile, liveNativeFile, "//"
      Path.Combine(stagingJsDir, "OrmTypes.d.ts"), Path.Combine(js, "OrmTypes.d.ts"), "//"
      Path.Combine(stagingJsDir, "Types.d.ts"), Path.Combine(js, "Types.d.ts"), "//"
      Path.Combine(stagingJsDir, "OrmMor.ts"), Path.Combine(js, "OrmMor.ts"), "//"
      Path.Combine(stagingJsDir, "CustomMor.ts"), Path.Combine(js, "CustomMor.ts"), "//" ]
  if profile.writeTypesFs then
    (Path.Combine(stagingSharedDir, "Types.fs"), Path.Combine(sh, "Types.fs"), "//") :: core
  else core

/// 行尾规范化：CRLF/CR → LF、逐行去尾空白、单个结尾换行；按画像决定是否补横幅。
/// 对同一文件幂等，故可直接用于在线文件的比对。
let text__normalized profile prefix (path: string) =
  let body =
    File.ReadAllText(path)
      .Replace("\r\n", "\n")
      .Replace("\r", "\n")
      .Split('\n')
    |> Array.map (fun line -> line.TrimEnd())
    |> String.concat "\n"
    |> fun text -> text.Trim('\n')
  if not profile.banner then body + "\n"
  else
    let bannerText = prefix + " AUTO-GENERATED by JCS TypeSys from " + profile.config.ns + "/Design-*.json. DO NOT EDIT."
    if body.StartsWith(bannerText, StringComparison.Ordinal) then body + "\n"
    else bannerText + "\n" + body + "\n"

let file__normalized profile prefix path =
  File.WriteAllText(path, text__normalized profile prefix path, UTF8Encoding(false))

/// 漂移比对。严格档（strictCheck）问「在线文件是否已处于规范形态」：只归一在线侧 CRLF，
/// **不补横幅/不去尾空白**，以免掩盖「在线文件缺横幅」这类真实差异；宽松档则两侧都规范化后比等价，
/// 与 WYI / jCopilot 原脚本一致（WYI 生成物历史上不带横幅，严格比会 100% 假漂移）。
let content__same profile prefix (staged: string) (live: string) =
  if not (File.Exists live) then false
  else
    let stagedText = text__normalized profile prefix staged
    if profile.strictCheck then
      String.Equals(File.ReadAllText(live).Replace("\r\n", "\n"), stagedText, StringComparison.Ordinal)
    else
      String.Equals(text__normalized profile prefix live, stagedText, StringComparison.Ordinal)

/// 生成器不补自定义类型的 open（如 jCopilot 的 CustomMor 用 `jCQT.AI.Model` 的 LlmModalType），
/// 且 `//[Reserved]{` 块每次重生成都为空，故在写盘前按画像注入。
let file__injected profile (path: string) =
  profile.injectOpens
  |> List.iter (fun (suffix, line) ->
    if path.EndsWith suffix then
      let text = File.ReadAllText path
      if not (text.Contains line) then
        File.WriteAllText(path, text.Replace("//[Reserved]{\n", "//[Reserved]{\n" + line + "\n"), UTF8Encoding(false)))

let dirs__staged profile =
  let slug = (Path.GetFileName profile.projectRoot).ToLowerInvariant()
  let root = Path.Combine(Path.GetTempPath(), slug + "-typesys-" + Guid.NewGuid().ToString("N"))
  let shared = Path.Combine(root, Path.GetRelativePath(profile.projectRoot, profile.config.mainDir))
  let js = Path.Combine(root, Path.GetRelativePath(profile.projectRoot, profile.config.JsDir))
  let liveNative = Path.Combine(profile.projectRoot, profile.config.ns + ".Native", "Native", "OrmMor.Native.fs")
  let stagedNative = Path.Combine(root, Path.GetRelativePath(profile.projectRoot, liveNative))
  root, shared, js, stagedNative, liveNative

/// 执行钉整条落地流水线。返回漂移文件数（Write 成功 / Check 通过均为 0）。
let run (output: string -> unit) (exeDir: string) (profile: Profile) (mode: Mode) =
  let root, shared, js, stagedNative, liveNative = dirs__staged profile
  Directory.CreateDirectory shared |> ignore
  Directory.CreateDirectory js |> ignore
  try
    Directory.GetFiles(profile.config.mainDir, "Design-*.json", SearchOption.TopDirectoryOnly)
    |> Array.iter (fun source ->
      File.Copy(source, Path.Combine(shared, Path.GetFileName source), true))

    // 生成器会保留 Types.fs 的 [TypeManaged] 区，故必须以在线版本为输入。
    File.Copy(Path.Combine(profile.config.mainDir, "Types.fs"), Path.Combine(shared, "Types.fs"), true)

    output $"TypeSys mode: {mode}"
    output $"Authoritative design root: {profile.config.mainDir}"
    output $"Isolated generation root: {root}"

    CodeRobot.go output exeDir { profile.config with mainDir = shared; JsDir = js }

    let legacyNative = Path.Combine(shared, "Native", "OrmMor.Native.fs")
    if File.Exists legacyNative then
      Directory.CreateDirectory(Path.GetDirectoryName stagedNative) |> ignore
      File.Move(legacyNative, stagedNative, true)

    let pairs =
      output__pairs profile shared js stagedNative liveNative
      |> List.filter (fun (staged, _, _) -> File.Exists staged)

    pairs
    |> List.iter (fun (staged, _, prefix) ->
      file__normalized profile prefix staged
      file__injected profile staged)

    let drift =
      pairs
      |> List.filter (fun (staged, live, prefix) -> not (content__same profile prefix staged live))

    match mode with
    | Check when drift.IsEmpty ->
      output $"TypeSys check passed: all {pairs.Length} generated outputs are current."
      0
    | Check ->
      drift
      |> List.iter (fun (_, live, _) -> output $"DRIFT {Path.GetRelativePath(profile.projectRoot, live)}")
      drift.Length
    | Write ->
      pairs
      |> List.iter (fun (staged, live, _) ->
        Directory.CreateDirectory(Path.GetDirectoryName live) |> ignore
        File.Copy(staged, live, true))
      output $"TypeSys write completed: {pairs.Length} generated outputs updated."
      0
  finally
    if Directory.Exists root then Directory.Delete(root, true)

/// 按 `C:/Dev/<Code>` 约定推导基础画像（ns / dbName / mainDir / JsDir 全部由 Code 决定）。
let profile__of devRoot code =
  let projectRoot = Path.Combine(devRoot, code)
  { config =
      { ns = code + ".Shared"
        rdbms = Rdbms.PostgreSql
        dbName = code.ToLowerInvariant()
        domainName = ""
        conn = ""
        mainDir = Path.Combine(projectRoot, code + ".Shared")
        JsDir = Path.Combine(projectRoot, "vscode", "src", "lib", "shared") }
    projectRoot = projectRoot
    banner = false
    writeTypesFs = false
    injectOpens = []
    strictCheck = false }

/// 在基础画像上叠加各项目的既有差异（与 WYI / Aiarwa / jCopilot 三个 Run-TypeSys-*.fsx 一一对应）。
let profile__project devRoot code =
  match code with
  | "Aiarwa" -> { profile__of devRoot code with banner = true; writeTypesFs = true; strictCheck = true }
  | "jCopilot" -> { profile__of devRoot code with injectOpens = [ "CustomMor.fs", "open jCQT.AI.Model" ] }
  | _ -> profile__of devRoot code

/// 可生成的项目 = `<Code>/<Code>.Shared/` 下确有 Design-*.json。
let codes__discover devRoot =
  Directory.GetDirectories devRoot
  |> Array.choose (fun d ->
    let code = Path.GetFileName d
    let shared = Path.Combine(d, code + ".Shared")
    if Directory.Exists shared && Directory.GetFiles(shared, "Design-*.json").Length > 0 then Some code
    else None)
  |> Array.sort
